version: "3.5"

services:
  redis:
    image: "redis:alpine"
  django:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - envs/django
      - envs/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/srv
  postgres:
    env_file:
      - envs/postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  celery:
    build: .
    command: celery -A websites worker -l info
    volumes:
      - .:/srv
    env_file:
      - envs/django
      - envs/postgres
    depends_on:
      - postgres
      - redis
volumes:
  postgres:
